#include <iostream>
#include <string>
#include <vector>
#include <iomanip>
#include <algorithm>
#include <stdexcept>
#include <fstream>
#include <sstream>

using std::vector;
using std::string;
using std::sort;
using std::cin;
using std::cout;
using std::stoi;
using std::setprecision;
using std::endl;
using std::setw;
using std::exception;
using std::ifstream;
using std::getline;
using std::istringstream;